pgose/walkacity

css/style.css
=> Margin auf 10

css/style.css
=> Reverse margin change

js/main.js
=> New Base map

js/main.js
Before you would have to find your location on the map, now you should just start at your centered point.
=> Recentered map to current user position

js/main.js
=> revenge smiley

css/style.css, index.html, js/main.js
green start button, red stop button, animation
=> start & stop button

css/style.css, js/main.js, walk/index.html
I have started working on the pop up and making the download trigger with the button of the popup instead of the link. It works but my computer has issues with the trajectory so I am trying to see if it works on my phone via vercel
=> Started implementing the popup

js/main.js, walk/index.html
I believe the main pop ups for rating and downloading should work!
=> Functional pop ups

css/style.css, heatmap/index.html, js/main.js, walk/index.html
header, footer, help window, walk button, heatmap button, user location with arrow
=> visualization 19.11

js/main.js
I originally wanted to adjust the entire csv file to the correct form, but sadly I didn't know how to make a proper linestring yet...So for the moment we have a 9 digit id for each point and a rating that is directly chosen by the slider. I'll ask how to create a linestring and a list of timestamps tomorrow ;)
=> trajectory id and rating

js/main.js
Please let me know if you can work with just lat and lon.
=> the correct format for the table. There are currently no geometries!

js/main.js
I have contacted the TAs responsible to give me permission to push WFS-T requests into the layer responsible for linking pgadmin with the geoserver.
=> prepared all necessary code for a geoserver push

js/main.js
If all goes well the trajectories can now be stored in the geodatabase. I only need to figure out how to prevent duplicate IDs.
=> the trajectories are now saved in the database

js/main.js
Before I had a compound PK with trajectory_id and point_id. Due to the nature of pgadmin and the primary keys, it wouldn't accept my randomly generated value as an input. So I only have the point_id as PK now.
=> only have the point_id as the primary key now

js/main.js, walk/index.html
I also added an alert like in the old download function if the local storage is empty and have no trajectories.
=> The UI buttons to confirm or cancel are now correct

walk/index.html
So it was inside the download pop up and would freeze the website...Now it doesn't anymore ;)
=> The help button in the html file got into a different dialog element

Backend/duplicate_key_check.py
Currently it is simply a function that returns the wanted highest ID number of the trajectory in the table. Has to somehow be given to the main.js script
=> The current maximum ID of trajectory

static/style.css, templates/heatmap.html
Has to be adjusted still but I made some slight cosmetic changes
=> template for info button

static/heatmap.js, static/main.js, static/style.css, templates/heatmap.html, templates/walk.html
I have added a bunch of different things in here. I also have designed a logo and would like to exchange that with the title text and make an about us page when you click on it. Sadly it doesn't work at the moment and I have asked for help.
=> Center button, continue button, info button

Backend/max_id.py, app.py, requirements.txt, static/main.js
Flask now provides the current highest id under `/js/max_id`
within `main.js`, pushing the trajectory now no longer calls `insertTrajectory()` directly, but instead calls a `$.ajax` GET request to `localhost/js/max_id`, increments it by 1 and then passes that value into `insertTrajectory()`.
=> SQL Indexation through Flask

static/heatmap.js, static/main.js, static/style.css, templates/heatmap.html, templates/walk.html
Cleaned up a lot of code and made some minor UI changes.
=> cleaned up code and made some minor UI changes.

static/style.css, templates/heatmap.html
=> added heatmap gradient

static/style.css, templates/heatmap.html
=> changed the values on the gradient to good/bad
